<a href="https://colab.research.google.com/github/sur-sakthy/data-visualisation-project/blob/main/Data/data_gathering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
# Code to read csv file into Colaboratory:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth, files
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [42]:
import pandas as pd
import requests
import json
import time

In [7]:
shareable_link = 'https://drive.google.com/file/d/1WiesJNCA-clZHwvKVKGMRU8QNWLtlTk1/view?usp=share_link'

downloaded = drive.CreateFile({'id':'1WiesJNCA-clZHwvKVKGMRU8QNWLtlTk1'}) 
downloaded.GetContentFile('unique_app_ids.csv')  
data = pd.read_csv('unique_app_ids.csv')
data

      App Id
0    1291340
1    1289310
2    1240210
3    1229490
4    1225330
..       ...
310     2870
311      620
312      420
313      240
314       70

[315 rows x 1 columns]

In [57]:
steamcharts = 'https://steamcharts.p.rapidapi.com/api/v1/games/'
headers = {
    'X-RapidAPI-Key': '4937138c4amshd89d92d21921ad8p16a3acjsnf8fad18ba097',
    'X-RapidAPI-Host': 'steamcharts.p.rapidapi.com'
}

dataset = pd.DataFrame()
for index, row in data.iterrows():
  # print(row['App Id'])
  response = requests.get(steamcharts + str(row['App Id']), headers=headers)
  if response.status_code != 200:
    print("Error fetching for App Id %d : %d" %(row['App Id'], response.status_code))
  else:
    response_object = json.loads(response.content)
    response_data = pd.DataFrame(response_object['stats'])
    response_data['id'] = response_object['id']
    response_data['name'] = response_object['name']
    response_data['playingTwelveHoursAgo'] = response_object['playingTwelveHoursAgo']
    response_data['twentyFourHourPeek'] = response_object['twentyFourHourPeek']
    response_data['allTimePeek'] = response_object['allTimePeek']
    dataset = dataset.append(response_data)
  time.sleep(6)

Error fetching for App Id 773951 : 404
Error fetching for App Id 772540 : 500
Error fetching for App Id 753420 : 500
Error fetching for App Id 732810 : 500
Error fetching for App Id 704850 : 500
Error fetching for App Id 686600 : 500
Error fetching for App Id 681660 : 500
Error fetching for App Id 619080 : 500
Error fetching for App Id 606280 : 500
Error fetching for App Id 583470 : 500
Error fetching for App Id 512900 : 500
Error fetching for App Id 481510 : 500
Error fetching for App Id 400940 : 500
Error fetching for App Id 390340 : 500
Error fetching for App Id 382310 : 500
Error fetching for App Id 337340 : 500
Error fetching for App Id 269950 : 500
Error fetching for App Id 236850 : 500
Error fetching for App Id 236510 : 500
Error fetching for App Id 218620 : 500

In [70]:
dataset

,month,averagePlayers,gain,gainInPercent,peakPlayers,id,name,playingTwelveHoursAgo,twentyFourHourPeek,allTimePeek
0,Last 30 Days,118.16,38.60,48.50,437,1291340,Townscaper,54,93,1162
1,September 2022,79.56,-5.66,-6.64,384,1291340,Townscaper,54,93,1162
2,August 2022,85.22,-8.35,-8.93,169,1291340,Townscaper,54,93,1162
3,July 2022,93.58,-8.48,-8.31,208,1291340,Townscaper,54,93,1162
4,June 2022,102.05,-61.94,-37.77,213,1291340,Townscaper,54,93,1162
...,...,...,...,...,...,...,...,...,...,...
119,November 2012,157.47,2.12,1.37,356,70,Half-Life,460,590,10480
120,October 2012,155.35,-61.41,-28.33,345,70,Half-Life,460,590,10480
121,September 2012,216.76,-19.78,-8.36,464,70,Half-Life,460,590,10480
122,August 2012,236.53,-115.83,-32.87,419,70,Half-Life,460,590,10480
123,July 2012,352.36,NaN,NaN,674,70,Half-Life,460,590,10480

In [63]:
dataset.to_csv('steam_charts.csv', sep=',', encoding='utf-8')

In [66]:
files.download('steam_charts.csv')